/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#0e131f",
        "surface-container": "#1a202c",
        "surface-tint": "#45dfa4",
        "outline-variant": "#3c4a42",
        "error-container": "#93000a",
        "surface-bright": "#343946",
        "inverse-surface": "#dde2f3",
        "primary": "#5af0b3",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#242a36",
        "on-tertiary-fixed-variant": "#4f319c",
        "on-error": "#690005",
        "inverse-primary": "#006c4b",
        "secondary-fixed-dim": "#2fd9f4",
        "secondary-container": "#00cbe6",
        "on-primary": "#003825",
        "tertiary-fixed-dim": "#cebdff",
        "tertiary-fixed": "#e8ddff",
        "on-primary-fixed-variant": "#005137",
        "primary-container": "#34d399",
        "surface-container-low": "#161c28",
        "violet-accent": "#a78bfa",
        "primary-fixed": "#68fcbf",
        "text-secondary": "#cbd5e1",
        "surface-container-lowest": "#080e1a",
        "on-surface-variant": "#bbcac0",
        "on-tertiary": "#381385",
        "on-background": "#dde2f3",
        "on-secondary-fixed-variant": "#004e5a",
        "secondary-fixed": "#a2eeff",
        "inverse-on-surface": "#2b303d",
        "tertiary": "#ddd0ff",
        "slate-surface": "rgba(15, 23, 42, 0.65)",
        "on-secondary": "#00363e",
        "secondary": "#5de6ff",
        "obsidian-base": "#030712",
        "on-surface": "#dde2f3",
        "on-secondary-fixed": "#001f25",
        "background": "#0e131f",
        "surface-variant": "#2f3542",
        "rose-expense": "#fb7185",
        "primary-fixed-dim": "#45dfa4",
        "on-primary-container": "#00563b",
        "error": "#ffb4ab",
        "on-tertiary-container": "#5335a0",
        "on-tertiary-fixed": "#21005e",
        "surface-dim": "#0e131f",
        "on-secondary-container": "#00515d",
        "surface-container-highest": "#2f3542",
        "emerald-glow": "#6ee7b7",
        "outline": "#85948b",
        "text-primary": "#f8fafc",
        "glass-border": "rgba(148, 163, 184, 0.12)",
        "tertiary-container": "#c4afff",
        "on-primary-fixed": "#002114"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter-mobile": "16px",
        "unit": "4px",
        "margin-page": "32px",
        "gutter-desktop": "24px",
        "card-padding": "24px",
        "sidebar-width": "280px"
      },
      fontFamily: {
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "body-bold": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md-mobile": ["Outfit", "sans-serif"],
        "body-base": ["Plus Jakarta Sans", "sans-serif"],
        "stat-lg": ["Outfit", "sans-serif"],
        "display-lg": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"]
      },
      fontSize: {
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "body-bold": ["14px", { "lineHeight": "22px", "letterSpacing": "0", "fontWeight": "600" }],
        "headline-md-mobile": ["20px", { "lineHeight": "28px", "fontWeight": "700" }],
        "body-base": ["14px", { "lineHeight": "22px", "letterSpacing": "0", "fontWeight": "500" }],
        "stat-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.03em", "fontWeight": "800" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
